FROM registry.redhat.io/ubi9/nodejs-18:latest AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY ui-distributed-tracing-pf4/web/package*.json web/
COPY ui-distributed-tracing-pf4/Makefile Makefile
RUN make install-frontend-ci

COPY ui-distributed-tracing-pf4/web/ web/
RUN make build-frontend

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.22 as go-builder

WORKDIR /opt/app-root

COPY ui-distributed-tracing-pf4/Makefile Makefile
COPY ui-distributed-tracing-pf4/go.mod go.mod
COPY ui-distributed-tracing-pf4/go.sum go.sum

RUN make install-backend

COPY ui-distributed-tracing-pf4/cmd/ cmd/
COPY ui-distributed-tracing-pf4/pkg/ pkg/

ENV GOFLAGS='-mod=mod'
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

RUN make build-backend BUILD_OPTS="-tags strictfipsruntime"

FROM registry.redhat.io/rhel9-4-els/rhel:9.4

RUN mkdir /licenses
COPY ui-distributed-tracing-pf4/LICENSE /licenses/.

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root

ENTRYPOINT ["/opt/app-root/plugin-backend", "-static-path", "/opt/app-root/web/dist"]

LABEL com.redhat.component="coo-distributed-tracing-console-plugin" \
      name="openshift/distributed-tracing-console-plugin" \
      version="v0.3.0" \
      summary="OpenShift console plugin to view and explore traces" \
      io.openshift.tags="openshift,observability-ui,distributed tracing" \
      io.k8s.display-name="OpenShift console distributed tracing plugin" \
      io.k8s.description="OpenShift console plugin to view and explore traces" \
      maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
      description="OpenShift console plugin to view and explore traces"
