FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY observability-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=1

# Build
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -a -tags netgo,osusergo -o manager cmd/operator/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.redhat.io/ubi8/ubi-minimal:8.10-1130
WORKDIR /

COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/must-gather/collection-scripts/* /usr/bin/
COPY --from=builder /workspace/LICENSE      /licenses/.
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="coo-operator" \
      name="Cluster Observability Operator" \
      version="v1.0.0" \
      summary="Cluster Observability Operator" \
      io.openshift.tags="openshift,observability" \
      io.k8s.display-name="Cluster Observability Operator" \
      io.k8s.description="Cluster Observability Operator enables administrators to create standalone monitoring stacks that are independently configurable for use by different services and users." \
      maintainer="Cluster Observability Operator Team <team-monitoring-incluster@redhat.com>" \
      description="Cluster Observability Operator"
