FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 as builder
ARG TARGETARCH

WORKDIR /src
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY cmd cmd
COPY pkg pkg
COPY main.go main.go

ENV GOOS=${TARGETOS:-linux}
ENV GOARCH=${TARGETARCH}
ENV CGO_ENABLED=1
ENV GOFLAGS=-mod=readonly
ENV GOEXPERIMENT=strictfipsruntime
RUN go build -tags strictfipsruntime -o /bin/cluster-health-analyzer

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

WORKDIR /
COPY --from=builder /bin/cluster-health-analyzer /bin/cluster-health-analyzer
USER 65532:65532

ENTRYPOINT ["/bin/cluster-health-analyzer", "serve"]

LABEL com.redhat.component="coo-cluster-health-analyzer" \
      name="openshift/cluster-health-analyzer" \
      version="v0.4.0" \
      summary="OpenShift Cluster Health Analyzer" \
      io.openshift.tags="openshift,observability,metrics,alerts,incidents" \
      io.k8s.display-name="COO Cluster Health Analyzer" \
      io.k8s.description="The Cluster Health Analyzer analyzes alerts and health signals, grouping related ones" \
      maintainer="Observability Intelligence Analytics Team <obsint-analytics@redhat.com>" \
      description="The Cluster Health Analyzer analyzes alerts and health signals, grouping related ones"
