FROM registry.redhat.io/ubi9/nodejs-18:latest AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY ui-troubleshooting-panel/web/package*.json web/
COPY ui-troubleshooting-panel/Makefile Makefile
RUN make install-frontend-ci

COPY ui-troubleshooting-panel/web/ web/
RUN make build-frontend

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.22 as go-builder

WORKDIR /opt/app-root

COPY ui-troubleshooting-panel/Makefile Makefile
COPY ui-troubleshooting-panel/go.mod go.mod
COPY ui-troubleshooting-panel/go.sum go.sum

RUN make install-backend

COPY ui-troubleshooting-panel/cmd/ cmd/
COPY ui-troubleshooting-panel/pkg/ pkg/

ENV GOFLAGS='-mod=mod'
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

RUN make build-backend BUILD_OPTS="-tags strictfipsruntime"

FROM registry.redhat.io/rhel9-2-els/rhel:9.2

RUN mkdir /licenses
COPY ui-troubleshooting-panel/LICENSE /licenses/.

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root

ENTRYPOINT ["/opt/app-root/plugin-backend", "-static-path", "/opt/app-root/web/dist"]

LABEL com.redhat.component="coo-troubleshooting-panel-console-plugin" \
      name="openshift/troubleshooting-panel-console-plugin" \
      version="v0.3.0" \
      summary="OpenShift console plugin to troubleshoot by correlating observability signals" \
      io.openshift.tags="openshift,observability-ui,korrel8r,correlation" \
      io.k8s.display-name="OpenShift console troubleshooting panel plugin" \
      maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
      description="OpenShift console plugin to troubleshoot by correlating observability signals"
