FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22 AS builder
WORKDIR /workspace

# Copy source files
COPY obo-prometheus-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=0

# Build
RUN make admission-webhook

FROM registry.redhat.io/ubi8/ubi-minimal:8.10-1086

COPY --from=builder workspace/admission-webhook /bin/admission-webhook
COPY --from=builder /workspace/LICENSE      /licenses/.

USER nobody

ENTRYPOINT ["/bin/admission-webhook"]

LABEL com.redhat.component="coo-po-admission-webhook" \
      name="prometheus-operator-admission-webhook" \
      version="v0.77.1" \
      summary="Admission Webhook for Prometheus Operator" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="Admission Webhook for Prometheus Operator" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      maintainer="Admission Webhook for Prometheus Operator" \
      description="Admission Webhook for Prometheus Operator" \
      io.k8s.description="Admission Webhook for Prometheus Operator"
