---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: -2025-06-23-17-34
  namespace: cluster-observabilit-tenant
spec:
  releasePlan: coo-fbc-v4-20-staging-release-plan
  snapshot: 
  data:
    releaseNotes:
      type: RHBA
      topic: "Cluster Observability Operator 1.2.0 release - fbc 4.4.20 - staging."
      issues:
        fixed:
          - id: COO-760
            source: issues.redhat.com
          - id: COO-970
            source: issues.redhat.com
      references:
        - https://access.redhat.com/security/updates/classification
