---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  namespace: cluster-observabilit-tenant
  name: coo-1.2.0-stage-release-cgs9t
spec:
  releasePlan: cluster-observability-operator-1-2-stage
  snapshot: cluster-observability-operator-1-2-chslz
  data:
    releaseNotes:
      type: RHBA
      topic: "Cluster Observability Operator 1.2.0 release - staging."
      issues:
        fixed:
          - id: COO-760
            source: issues.redhat.com
          - id: COO-970
            source: issues.redhat.com
      references:
        - https://access.redhat.com/security/updates/classification
